Repository eduNEXT/eox-hooks, pull requests merged in 2023-01, with the labels that each got.

#35 fix: adding a fake request to execute in async servers
  eox_hooks/actions.py
  eox_hooks/utils.py
Labels: size/s

#32 Receiver to catch persistent grade event.
  eox_hooks/apps.py
Labels: size/xs

#39 feat(DS-367): add compatibility with Open edX olive release
  .github/ ISSUE_TEMPLATE /bug_report.md
  .github/ ISSUE_TEMPLATE /feature_request.md
  .github/pull_request_template.md
  .github/workflows/bumpversion.yml
  .github/workflows/labeler.yml
  .github/workflows/tests.yml
  README.rst
  eox_hooks/utils.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/django.txt
  requirements/pip-tools.txt
  requirements/test.txt
  requirements/tox.txt
  tox.ini
Labels: size/m
